# redisson single 单节点模式参数配置
singleServerConfig:
  # 连接空闲超时，单位：毫秒
  idleConnectionTimeout: 10000
  # 连接超时，单位：毫秒
  connectTimeout: 10000
  # 命令等待超时，单位：毫秒
  timeout: 3000
  # 命令失败重试次数
  retryAttempts: 3
  # 命令重试发送时间间隔，单位：毫秒
  retryInterval: 1500
  # 密码
  password: null
  # 单个连接最大订阅数量
  subscriptionsPerConnection: 5
  # 客户端名称
  clientName: null
  # 节点地址
  address: "redis://127.0.0.1:6379"
  # 发布和订阅连接的最小空闲连接数
  subscriptionConnectionMinimumIdleSize: 1
  # 发布和订阅连接池大小
  subscriptionConnectionPoolSize: 50
  # 最小空闲连接数
  connectionMinimumIdleSize: 32
  # 连接池大小
  connectionPoolSize: 64
  # 数据库编号
  database: 0
  # DNS 监测时间间隔，单位：毫秒
  dnsMonitoringInterval: 5000
  # 启用 SSL 终端识别
  # sslEnableEndpointIdentification: true
  # SSL 实现方式
  # sslProvider: JDK
  # SSL 信任证书库路径
  # sslTruststore: null
  # SSL信任证书库密码
  # sslTruststorePassword: null
  # SSL钥匙库路径
  # sslKeystore: null
  # SSL钥匙库密码
  # sslKeystorePassword: null
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: NIO


